// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgAMzGxkr8irwAXMCsSx5OC7jM8roHz_o',
    appId: '1:572795362174:web:f82b585ff6edbe2d7bf12f',
    messagingSenderId: '572795362174',
    projectId: 'graduation-project-c9b8a',
    authDomain: 'graduation-project-c9b8a.firebaseapp.com',
    storageBucket: 'graduation-project-c9b8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB874MECPVIu9gAWSHSuJBTJYc3pE8X2CE',
    appId: '1:572795362174:android:f851903a66d52f8b7bf12f',
    messagingSenderId: '572795362174',
    projectId: 'graduation-project-c9b8a',
    storageBucket: 'graduation-project-c9b8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVLkKIC9VxsM3vB3U8VDEjfAL4cPVUDjQ',
    appId: '1:572795362174:ios:fc463ea53cfa82667bf12f',
    messagingSenderId: '572795362174',
    projectId: 'graduation-project-c9b8a',
    storageBucket: 'graduation-project-c9b8a.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgAMzGxkr8irwAXMCsSx5OC7jM8roHz_o',
    appId: '1:572795362174:web:06d76cb8e89bc7b97bf12f',
    messagingSenderId: '572795362174',
    projectId: 'graduation-project-c9b8a',
    authDomain: 'graduation-project-c9b8a.firebaseapp.com',
    storageBucket: 'graduation-project-c9b8a.firebasestorage.app',
  );
}
